### ISSUE TITLE
Parsing mpiblast results

### ISSUE THREAD

**Issue by arundurvasula** [pjotrp/blastxmlparser#5]
Hi,

Thanks a lot for writing this! I'm running into an issue that I hope you can help me solve. I'm running MPIBlast with XML output and would like to be able to summarize it. Unfortunately, mpiblast seems to cat together different blast results, which includes the ending line and the start of the next search:

          </BlastOutput_iterations>
    </BlastOutput>
    <?xml version="1.0"?>

Is there a way for blastxml parser to keep going after this and display all hits? (right now it only displays 2 hsps)

Once again, thanks a lot for writing this!

**Comment by pjotrp** [comment]
mpiblast is generating invalid XML. Either fix it upstream or parse the file to make it valid.
